name: linting, testing, building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        if: always()

      - name: Lint TypeScript
        run: npm run lint:ts
        if: always()

      - name: Lint SCSS
        run: npm run lint:scss
        if: always()

      - name: Build project
        run: npm run build:prod
        if: always()

      - name: Run unit tests
        run: npm run test:unit
        if: always()

      - name: Run storybook
        run: npm run storybook:build  
        if: always()
